---
services:
  generative-agents:
    container_name: generative-agents
    image: ghcr.io/JustPersona/generative-agents-docker:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./share:/share
    environment:
      TZ: "Asia/Seoul"
      PUID: 1000
      PGID: 1000
      OLLAMA_CONFIG_ENABLED: true
      OLLAMA_HOST: "ollama"
      OLLAMA_PORT: 11434
      OLLAMA_ACTION: "pull"
      OLLAMA_MODEL_NAME: "llama3.2:1b"
      OLLAMA_GGUF_DOWNLOAD_URL: ""
      OLLAMA_GGUF_PATH: "persona.gguf"
      OLLAMA_MODELFILE_PATH: "Modelfile"
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
      - ./share:/share
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
